import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import { headers } from "next/headers";
import { fallbackLng, headerName, Languages } from "@/translation/settings";
import { dir } from "i18next";
import "@/styles/globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const h = await headers();

  // header setado pelo middleware
  const raw = h.get(headerName) as Languages | null;
  const lng: Languages = raw ?? fallbackLng;

  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={`${poppins.className} ${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
